/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolaboratorioclase.gui;

import entidades.producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trabajonumero6lab.gui.principal;

/**
 *
 * @author Frank
 */
public class consultaPorPrecio extends javax.swing.JInternalFrame {
    DefaultTableModel mt = new DefaultTableModel();
    /**
     * Creates new form consultaPorPrecio
     */
    public consultaPorPrecio() {
        initComponents();
        String ids [] = {"Codigo","Precio","Descripcion","Stock"};
        mt.setColumnIdentifiers(ids);
        jTable1.setModel(mt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPrecioMinimo = new javax.swing.JTextField();
        jPrecioMaximo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        consultaPrecio = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta por precio");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("(Precio minimo): ");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("(Precio Maximo):");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        consultaPrecio.setText("Consultar");
        consultaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultaPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPrecioMaximo)
                            .addComponent(jPrecioMinimo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPrecioMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPrecioMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(consultaPrecio)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPrecioActionPerformed
        // TODO add your handling code here:
        double pMinimo;
        double pMaximo;
        boolean Encontrado = false;
        
        try{
            pMinimo = Double.parseDouble(jPrecioMinimo.getText());
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,"Error(No se ingresó un numero)");
            jPrecioMinimo.setText("");
            jPrecioMinimo.requestFocus();
            return;
        }
        
        try{
            pMaximo = Double.parseDouble(jPrecioMaximo.getText());
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,"Error(No se ingresó un numero)");
            jPrecioMaximo.setText("");
            jPrecioMaximo.requestFocus();
            return;
        }
        
        borrarFilas();
        for(producto p : principal.getProductos()){
            if(p.getPrecio() >= pMinimo && p.getPrecio() <= pMaximo){
                mt.addRow(new Object[]{
                p.getCodigo(),
                p.getPrecio(),
                p.getDescripcion(),
                p.getStock()
                });
                Encontrado = true;
            }
        }
        
        if(!Encontrado){
            JOptionPane.showMessageDialog(this,"No se encontró un producto entre el rango de precio...");
        }
        
        
    }//GEN-LAST:event_consultaPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jPrecioMaximo;
    private javax.swing.JTextField jPrecioMinimo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
public void borrarFilas(){
        int filas = jTable1.getRowCount() - 1;
        for(int f = filas ; f >= 0;f--){
            mt.removeRow(f);
        }
    }
}
